name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        emacs_version:
          - 27.2
          - 28.2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: |
          emacs -Q --batch -L . -l flymake-textlint-tests.el -f ert-run-tests-batch-and-exit
